#!/usr/bin/env python3
"""Generates src/game/coop_setup_font.h: a 1-bit, 10x20 terminal font for
the first-run setup screen (shown before the game's own fonts are
available), rasterized from Noto Sans Mono Bold (SIL OFL 1.1, see
third_party/fonts/OFL.txt).

    tools/gen_terminal_font.py /path/to/NotoSansMono-Bold.ttf > src/game/coop_setup_font.h
"""

import sys

from PIL import Image, ImageDraw, ImageFont

WIDTH = 10
HEIGHT = 20
FIRST = 32
LAST = 126

font = ImageFont.truetype(sys.argv[1], 16)
ascent, _ = font.getmetrics()

print("// Generated by tools/gen_terminal_font.py - do not edit.")
print("//")
print("// Glyph data derived from Noto Sans Mono Bold, Copyright 2015-2020")
print("// Google LLC, licensed under the SIL Open Font License, Version 1.1")
print("// (third_party/fonts/OFL.txt). This file is under the same license.")
print()
print("#ifndef FALLOUT_GAME_COOP_SETUP_FONT_H_")
print("#define FALLOUT_GAME_COOP_SETUP_FONT_H_")
print()
print("namespace fallout {")
print()
print("#define COOP_SETUP_FONT_WIDTH %d" % WIDTH)
print("#define COOP_SETUP_FONT_HEIGHT %d" % HEIGHT)
print("#define COOP_SETUP_FONT_FIRST %d" % FIRST)
print("#define COOP_SETUP_FONT_LAST %d" % LAST)
print()
print("// One row per entry, bit %d is the leftmost pixel." % (WIDTH - 1))
print("static const unsigned short coop_setup_font[%d][%d] = {" % (LAST - FIRST + 1, HEIGHT))

for code in range(FIRST, LAST + 1):
    image = Image.new("L", (WIDTH, HEIGHT), 0)
    draw = ImageDraw.Draw(image)
    left = font.getlength(chr(code))
    draw.text(((WIDTH - left) / 2, 15 - ascent), chr(code), font=font, fill=255)
    rows = []
    for y in range(HEIGHT):
        bits = 0
        for x in range(WIDTH):
            if image.getpixel((x, y)) >= 110:
                bits |= 1 << (WIDTH - 1 - x)
        rows.append("0x%03X" % bits)
    label = chr(code).replace("\\", "backslash")
    print("    { %s }, // '%s'" % (", ".join(rows), label))

print("};")
print()
print("} // namespace fallout")
print()
print("#endif /* FALLOUT_GAME_COOP_SETUP_FONT_H_ */")
